
// Objective-C API for talking to the following Go packages
//
//	github.com/dpwiese/go-gomobile-demo
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Sample_FRAMEWORK_H__
#define __Sample_FRAMEWORK_H__

#include "Sample.objc.h"
#include "Universe.objc.h"

#endif
